name: Python EXE Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller==6.9.0

      - name: Build EXE
        run: pyinstaller --add-data 'assets/*:assets' --add-data 'assets/image/*:assets/image' --onefile --windowed -i .\assets\app_icon.ico main.py

      - name: Rename EXE
        run: |
          move dist\main.exe dist\Multi-process-downloader_x86-64.exe

      - name: Upload
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist\Multi-process-downloader_x86-64.exe
